import { CarProps } from "@/types";
export const mockCars: CarProps[] = [
  {
    city_mpg: 28,
    class: "compact car",
    combination_mpg: 32,
    cylinders: 4,
    displacement: 1.6,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 37,
    make: "Toyota",
    model: "Corolla",
    transmission: "a",
    year: 2020,
  },
  {
    city_mpg: 30,
    class: "compact car",
    combination_mpg: 34,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 40,
    make: "Honda",
    model: "Civic",
    transmission: "a",
    year: 2001,
  },
  {
    city_mpg: 27,
    class: "midsize car",
    combination_mpg: 31,
    cylinders: 4,
    displacement: 2.5,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 36,
    make: "Nissan",
    model: "Altima",
    transmission: "a",
    year: 1999,
  },
  {
    city_mpg: 22,
    class: "midsize suv",
    combination_mpg: 25,
    cylinders: 6,
    displacement: 3.5,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 30,
    make: "Ford",
    model: "Edge",
    transmission: "a",
    year: 2018,
  },
  {
    city_mpg: 18,
    class: "large suv",
    combination_mpg: 21,
    cylinders: 8,
    displacement: 5.3,
    drive: "4wd",
    fuel_type: "gas",
    highway_mpg: 26,
    make: "Chevrolet",
    model: "Tahoe",
    transmission: "a",
    year: 1970,
  },
  {
    city_mpg: 25,
    class: "compact suv",
    combination_mpg: 28,
    cylinders: 4,
    displacement: 2.4,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 33,
    make: "Hyundai",
    model: "Tucson",
    transmission: "a",
    year: 2021,
  },
  {
    city_mpg: 29,
    class: "compact car",
    combination_mpg: 33,
    cylinders: 4,
    displacement: 1.5,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 39,
    make: "Kia",
    model: "Forte",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 17,
    class: "pickup truck",
    combination_mpg: 20,
    cylinders: 6,
    displacement: 3.6,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 25,
    make: "Ram",
    model: "1500",
    transmission: "a",
    year: 2018,
  },
  {
    city_mpg: 24,
    class: "midsize suv",
    combination_mpg: 27,
    cylinders: 4,
    displacement: 2.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 31,
    make: "Mazda",
    model: "CX-5",
    transmission: "a",
    year: 2021,
  },
  {
    city_mpg: 33,
    class: "compact car",
    combination_mpg: 36,
    cylinders: 4,
    displacement: 1.4,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 42,
    make: "Volkswagen",
    model: "Jetta",
    transmission: "a",
    year: 2020,
  },
  {
    city_mpg: 22,
    class: "midsize suv",
    combination_mpg: 25,
    cylinders: 6,
    displacement: 3.3,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 29,
    make: "Kia",
    model: "Sorento",
    transmission: "a",
    year: 2019,
  },
  {
    city_mpg: 23,
    class: "midsize car",
    combination_mpg: 27,
    cylinders: 4,
    displacement: 2.5,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 34,
    make: "Toyota",
    model: "Camry",
    transmission: "a",
    year: 2019,
  },
  {
    city_mpg: 26,
    class: "crossover",
    combination_mpg: 30,
    cylinders: 4,
    displacement: 2.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 35,
    make: "Subaru",
    model: "Forester",
    transmission: "a",
    year: 2021,
  },
  {
    city_mpg: 21,
    class: "sedan",
    combination_mpg: 24,
    cylinders: 6,
    displacement: 3.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 30,
    make: "BMW",
    model: "530i",
    transmission: "a",
    year: 2018,
  },
  {
    city_mpg: 34,
    class: "compact car",
    combination_mpg: 37,
    cylinders: 4,
    displacement: 1.8,
    drive: "fwd",
    fuel_type: "hybrid",
    highway_mpg: 43,
    make: "Toyota",
    model: "Prius",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 16,
    class: "luxury suv",
    combination_mpg: 19,
    cylinders: 8,
    displacement: 4.4,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 24,
    make: "BMW",
    model: "X5",
    transmission: "a",
    year: 2017,
  },
  {
    city_mpg: 20,
    class: "compact suv",
    combination_mpg: 24,
    cylinders: 4,
    displacement: 2.4,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 29,
    make: "Jeep",
    model: "Compass",
    transmission: "a",
    year: 2020,
  },
  {
    city_mpg: 19,
    class: "suv",
    combination_mpg: 22,
    cylinders: 6,
    displacement: 3.7,
    drive: "4wd",
    fuel_type: "gas",
    highway_mpg: 27,
    make: "Ford",
    model: "Explorer",
    transmission: "a",
    year: 2019,
  },
  {
    city_mpg: 32,
    class: "compact car",
    combination_mpg: 35,
    cylinders: 4,
    displacement: 1.5,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 41,
    make: "Hyundai",
    model: "Elantra",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 35,
    class: "compact hatchback",
    combination_mpg: 38,
    cylinders: 4,
    displacement: 1.2,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 43,
    make: "Mitsubishi",
    model: "Mirage",
    transmission: "a",
    year: 2021,
  },
  {
    city_mpg: 30,
    class: "compact car",
    combination_mpg: 34,
    cylinders: 4,
    displacement: 1.6,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 40,
    make: "Audi",
    model: "A3",
    transmission: "a",
    year: 2019,
  },
  {
    city_mpg: 20,
    class: "luxury suv",
    combination_mpg: 23,
    cylinders: 6,
    displacement: 3.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "Mercedes-Benz",
    model: "GLE 350",
    transmission: "a",
    year: 2020,
  },
  {
    city_mpg: 120,
    class: "sedan",
    combination_mpg: 118,
    cylinders: 0,
    displacement: 0.0,
    drive: "awd",
    fuel_type: "electricity",
    highway_mpg: 115,
    make: "Tesla",
    model: "Model 3",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 25,
    class: "compact suv",
    combination_mpg: 28,
    cylinders: 4,
    displacement: 2.4,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 33,
    make: "Chevrolet",
    model: "Equinox",
    transmission: "a",
    year: 2016,
  },
  {
    city_mpg: 33,
    class: "compact car",
    combination_mpg: 37,
    cylinders: 4,
    displacement: 1.3,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 41,
    make: "Fiat",
    model: "500",
    transmission: "a",
    year: 2017,
  },
  {
    city_mpg: 22,
    class: "pickup truck",
    combination_mpg: 25,
    cylinders: 6,
    displacement: 3.6,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 29,
    make: "GMC",
    model: "Canyon",
    transmission: "a",
    year: 2020,
  },
  {
    city_mpg: 27,
    class: "compact car",
    combination_mpg: 31,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 35,
    make: "Mazda",
    model: "Mazda3",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 28,
    class: "crossover",
    combination_mpg: 31,
    cylinders: 4,
    displacement: 2.5,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 36,
    make: "Subaru",
    model: "Outback",
    transmission: "a",
    year: 2019,
  },
  {
    city_mpg: 40,
    class: "compact hatchback",
    combination_mpg: 44,
    cylinders: 4,
    displacement: 1.6,
    drive: "fwd",
    fuel_type: "hybrid",
    highway_mpg: 47,
    make: "Hyundai",
    model: "Ioniq",
    transmission: "a",
    year: 2021,
  },
  {
    city_mpg: 24,
    class: "luxury sedan",
    combination_mpg: 28,
    cylinders: 4,
    displacement: 2.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 34,
    make: "Volvo",
    model: "S60",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 16,
    class: "sports car",
    combination_mpg: 19,
    cylinders: 8,
    displacement: 5.0,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 25,
    make: "Ford",
    model: "Mustang",
    transmission: "a",
    year: 2018,
  },
  {
    city_mpg: 21,
    class: "midsize suv",
    combination_mpg: 24,
    cylinders: 6,
    displacement: 3.5,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 30,
    make: "Lexus",
    model: "RX 350",
    transmission: "a",
    year: 2020,
  },
  {
    city_mpg: 31,
    class: "compact car",
    combination_mpg: 35,
    cylinders: 4,
    displacement: 1.6,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 40,
    make: "Nissan",
    model: "Sentra",
    transmission: "a",
    year: 2017,
  },
  {
    city_mpg: 29,
    class: "compact car",
    combination_mpg: 32,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 36,
    make: "Volkswagen",
    model: "Golf",
    transmission: "a",
    year: 2021,
  },
  {
    city_mpg: 110,
    class: "sedan",
    combination_mpg: 105,
    cylinders: 0,
    displacement: 0,
    drive: "awd",
    fuel_type: "electricity",
    highway_mpg: 102,
    make: "BMW",
    model: "i4",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 19,
    class: "suv",
    combination_mpg: 23,
    cylinders: 6,
    displacement: 3.6,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 27,
    make: "Buick",
    model: "Enclave",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 26,
    class: "compact suv",
    combination_mpg: 30,
    cylinders: 4,
    displacement: 2.4,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 34,
    make: "Jeep",
    model: "Renegade",
    transmission: "a",
    year: 2020,
  },
  {
    city_mpg: 22,
    class: "luxury car",
    combination_mpg: 26,
    cylinders: 6,
    displacement: 3.0,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 32,
    make: "Cadillac",
    model: "CT5",
    transmission: "a",
    year: 2021,
  },
  {
    city_mpg: 18,
    class: "suv",
    combination_mpg: 21,
    cylinders: 6,
    displacement: 4.0,
    drive: "4wd",
    fuel_type: "gas",
    highway_mpg: 26,
    make: "Toyota",
    model: "4Runner",
    transmission: "a",
    year: 2019,
  },
  {
    city_mpg: 23,
    class: "compact car",
    combination_mpg: 27,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 33,
    make: "Kia",
    model: "Rio",
    transmission: "a",
    year: 2016,
  }

];
